/* Le Pot Magique 2.0 — application 100 % statique, sans serveur.
 * Données personnelles : conservées dans le navigateur, jamais envoyées par le site.
 * Une nouvelle classe démarre vide ; les classes déjà enregistrées sont conservées.
 */
'use strict';
const VISUALS=[{id:'sticks',name:'Bâtonnets',emoji:'🪵'},{id:'pencils',name:'Crayons',emoji:'✏️'},{id:'wheel',name:'Roue',emoji:'🎡'},{id:'cards',name:'Cartes',emoji:'🃏'},{id:'balls',name:'Boules',emoji:'🎱'}];
const AVATAR_COLORS=['#e8f0df','#f2e8f8','#ffecdf','#f8e9ef','#e0edf7'];
const PASTEL_COLORS=['#b6d7bc','#dac8ef','#f5cdb5','#f4d8e4','#f3dfab','#c6dce9','#d3e8c6','#e8d4bf'];
const HELP={
  random:{title:'Tirage 100 % aléatoire',body:'Chaque élève présent qui n’a pas encore été tiré pendant le tour en cours possède exactement la même probabilité d’être sélectionné. Les interrogations passées ne changent pas cette probabilité. Avec 20 élèves éligibles, chacun a 5 % de chances.'},
  fair:{title:'Tirage équitable',body:'Le hasard reste présent, mais les chances sont pondérées selon le nombre d’interrogations confirmées par jour de présence lors des 20 derniers jours de classe enregistrés. Plus ce taux est faible, plus la probabilité est élevée. Les élèves absents et ceux déjà tirés dans le tour restent exclus. La formule utilisée est poids = 1 ÷ (0,5 + interrogations ÷ jours de présence) ; la probabilité est le poids de l’élève divisé par la somme des poids des élèves éligibles.'},
  times:{title:'Nombre d’interrogations',body:'Nombre de réponses orales réellement confirmées pour cet élève ou cette période. Un tirage annulé ne compte jamais.'},
  share:{title:'Part des interrogations',body:'Pourcentage des interrogations de la classe attribuées à un élève : nombre de ses interrogations ÷ total des interrogations confirmées × 100. Ce n’est pas sa probabilité d’être tiré.'},
  presenceRate:{title:'Interrogations par jour de présence',body:'Nombre d’interrogations confirmées ÷ nombre de journées où l’élève était marqué présent. Les journées ne sont comptées que si la présence a été enregistrée dans l’application ; cela évite de supposer qu’un élève est présent tous les jours.'},
  coverage:{title:'Couverture de la classe',body:'Pourcentage d’élèves présents au moins une fois pendant la période qui ont été interrogés au moins une fois. Un élève interrogé trois fois compte une seule fois pour cet indicateur.'},
  eligible:{title:'Élèves éligibles',body:'Ce sont les élèves présents qui ne sont pas encore passés pendant le tour actuel. Un nouveau tour remet tous les bâtonnets en jeu sans effacer les statistiques.'},
  probability:{title:'Probabilité du prochain tirage',body:'Pourcentage de chances de sortir au prochain tirage seulement. En mode aléatoire, tous les élèves éligibles ont la même chance. En mode équitable, les poids sont ajustés par les participations et les jours de présence enregistrés.'},
  attendance:{title:'Présences prises en compte',body:'La première utilisation du tirage ou une modification des absences enregistre la présence de la classe pour cette date. Un jour où le site n’est pas utilisé n’est pas supposé être un jour de présence. Vous pouvez corriger les présences depuis l’historique.'},
  equity:{title:'Écart de participation',body:'Compare le nombre d’interrogations par jour de présence, et pas seulement le nombre total d’interrogations. Cet outil sert à repérer d’éventuels écarts, sans juger les élèves ni garantir un nombre identique de prises de parole.'},
  subject:{title:'Matières',body:'La matière sélectionnée est enregistrée avec chaque interrogation. Vous pourrez ensuite filtrer les statistiques par français, mathématiques, histoire ou toute autre matière que vous ajouterez.'},
  stored:{title:'Vos données restent sur cet appareil',body:'GitHub Pages affiche le site, mais n’héberge pas votre suivi. Les données sont conservées localement dans ce navigateur. Pour changer d’ordinateur ou éviter une perte si Chrome est réinitialisé, exportez régulièrement une sauvegarde JSON.'}
};
const $=(sel,root=document)=>root.querySelector(sel);
const $$=(sel,root=document)=>Array.from(root.querySelectorAll(sel));
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ic=(id,cls='')=>`<svg aria-hidden="true" class="icon ${cls}"><use href="#i-${id}"></use></svg>`;
const help=(key)=>`<button class="help-dot" type="button" data-action="help" data-key="${esc(key)}" title="Comprendre cet indicateur" aria-label="Comprendre : ${esc(HELP[key]?.title||key)}">?</button>`;
const uid=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'id'+Date.now().toString(36)+Math.random().toString(36).slice(2,10);
const isoDay=(date=new Date())=>{const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const dateObj=s=>new Date(`${s}T12:00:00`);
const fmtDate=(s,opts={weekday:'long',day:'numeric',month:'long'})=>dateObj(s).toLocaleDateString('fr-FR',opts);
const fmtInt=n=>Number(n||0).toLocaleString('fr-FR');
const fmtPct=n=>`${(n||0).toLocaleString('fr-FR',{maximumFractionDigits:1})} %`;
const fmtRate=n=>(n||0).toLocaleString('fr-FR',{maximumFractionDigits:2});
const startOfWeek=s=>{const d=dateObj(s);d.setDate(d.getDate()-((d.getDay()+6)%7));return isoDay(d)};
const schoolYearLabel=()=>{const d=new Date(),start=d.getMonth()>=7?d.getFullYear():d.getFullYear()-1;return `${start}-${start+1}`};
const clone=value=>JSON.parse(JSON.stringify(value));
const initialLayout=()=>({id:uid(),name:'Ma disposition',items:[
  {id:uid(),type:'board',x:30,y:3,rotation:0,studentIds:[]},
  {id:uid(),type:'desk2',x:17,y:23,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'desk2',x:58,y:23,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'desk2',x:17,y:47,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'desk2',x:58,y:47,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'desk2',x:17,y:72,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'desk2',x:58,y:72,rotation:0,studentIds:[null,null]},
  {id:uid(),type:'teacher',x:80,y:5,rotation:0,studentIds:[]},
  {id:uid(),type:'window',x:1,y:37,rotation:90,studentIds:[]},
  {id:uid(),type:'door',x:92,y:85,rotation:0,studentIds:[]}
]});
function makeYear(label,seed=[]){const layout=initialLayout();return {id:uid(),label,createdAt:new Date().toISOString(),students:seed.map(s=>typeof s==='string'?{id:uid(),name:s,active:true,addedOn:isoDay()}:{id:s.id||uid(),name:s.name,active:true,addedOn:isoDay()}),attendance:{},events:[],observations:[],questions:[],layouts:[layout],activeLayoutId:layout.id,round:[],classDays:[]};}
const makeState=()=>{const y=makeYear(schoolYearLabel());return {version:2,activeYearId:y.id,years:[y],preferences:{confetti:true,reducedMotion:false},visual:'sticks',mode:'random',subject:'',askQuestion:false};};
let S=null;
const UI={page:'tirage',statsPeriod:'week',statsFrom:isoDay(),statsTo:isoDay(),statsSubject:'',studentFilter:'',selectedStudentId:'',calendarMonth:isoDay().slice(0,7)+'-01',calendarSelected:isoDay(),selectedLayoutItemId:'',pending:null,lastResult:null,animating:false,projector:false,toastTimer:null,importing:false};
const yr=()=>S.years.find(y=>y.id===S.activeYearId)||S.years[0];
const studentById=id=>yr().students.find(s=>s.id===id);
const activeStudents=()=>yr().students.filter(s=>s.active);
const today=()=>isoDay();
const todayAttendance=()=>yr().attendance[today()]||{};
const isAbsent=(id,date=today())=>yr().attendance[date]?.[id]==='absent';
const hasConfirmed=id=>yr().events.some(e=>e.studentId===id);
const getEligible=()=>activeStudents().filter(s=>!isAbsent(s.id)&&!yr().round.includes(s.id));
const getLayout=()=>yr().layouts.find(l=>l.id===yr().activeLayoutId)||yr().layouts[0];
const subjects=()=>[...new Set(['Sans matière','Français','Mathématiques','Histoire','Géographie','Sciences','Anglais','Lecture',...yr().questions.map(q=>q.subject),...yr().events.map(e=>e.subject).filter(Boolean)])];
const subjectOptions=(chosen='',includeAll=false)=>`${includeAll?'<option value="">Toutes les matières</option>':''}${subjects().map(s=>`<option value="${esc(s)}" ${s===chosen?'selected':''}>${esc(s)}</option>`).join('')}`;
const rand=()=>{if(typeof crypto!=='undefined'&&crypto.getRandomValues){const v=new Uint32Array(1);crypto.getRandomValues(v);return v[0]/4294967296}return Math.random()};
const pickUniform=arr=>arr[Math.floor(rand()*arr.length)];
const pastelFor=i=>PASTEL_COLORS[i%PASTEL_COLORS.length];
const avatarColor=i=>AVATAR_COLORS[i%AVATAR_COLORS.length];
const ensureAttendanceDay=(date=today())=>{const y=yr();if(!y.attendance[date]){y.attendance[date]={};y.students.filter(s=>s.active).forEach(s=>y.attendance[date][s.id]='present');}if(!y.classDays.includes(date))y.classDays.push(date);};
const rateWindowDays=()=>yr().classDays.filter(d=>d<=today()).sort().slice(-20);
function equityData(candidates=getEligible()){
  const days=rateWindowDays();
  const counts=new Map();const presence=new Map();
  candidates.forEach(s=>{counts.set(s.id,yr().events.filter(e=>e.studentId===s.id&&days.includes(eventDay(e))).length);presence.set(s.id,days.filter(d=>yr().attendance[d]?.[s.id]==='present').length)});
  const weights=candidates.map(s=>{const p=Math.max(1,presence.get(s.id));const perDay=counts.get(s.id)/p;return {id:s.id,person:s,count:counts.get(s.id),presentDays:presence.get(s.id),rate:perDay,weight:1/(.5+perDay)}});
  const total=weights.reduce((sum,r)=>sum+r.weight,0);
  return weights.map(r=>({...r,probability:total?100*r.weight/total:0}));
}
function pickCandidate(){const eligible=getEligible();if(!eligible.length)return null;if(S.mode==='random')return pickUniform(eligible);const weights=equityData(eligible);const draw=rand()*weights.reduce((sum,r)=>sum+r.weight,0);let cumulative=0;for(const entry of weights){cumulative+=entry.weight;if(draw<cumulative)return entry.person;}return weights.at(-1).person;}
/* Sauvegarde séquentielle pour ne jamais écraser une modification plus récente. */
let dbPromise=null,writeQueue=Promise.resolve(),backend='IndexedDB';
function openDB(){if(!('indexedDB'in window))return Promise.reject(new Error('IndexedDB indisponible'));if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('le-pot-magique',1);request.onupgradeneeded=()=>request.result.createObjectStore('app');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return dbPromise;}
async function readState(){try{const db=await openDB();return await new Promise((resolve,reject)=>{const req=db.transaction('app','readonly').objectStore('app').get('state');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}catch(err){backend='localStorage';try{return JSON.parse(localStorage.getItem('le-pot-magique-v2')||'null')}catch(e){return null}}}
async function writeState(snapshot){if(backend==='localStorage'){localStorage.setItem('le-pot-magique-v2',JSON.stringify(snapshot));return;}try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('app','readwrite');tx.objectStore('app').put(snapshot,'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}catch(err){backend='localStorage';localStorage.setItem('le-pot-magique-v2',JSON.stringify(snapshot));}}
function save(){const snapshot=clone(S);writeQueue=writeQueue.catch(()=>{}).then(()=>writeState(snapshot)).then(()=>{const el=$('#saveStatus');if(el)el.textContent='Données enregistrées sur cet appareil';}).catch(e=>{console.error('Erreur de sauvegarde',e);const el=$('#saveStatus');if(el)el.textContent='Attention : sauvegarde impossible. Exportez vos données.';toast('Sauvegarde impossible : vérifiez l’espace disponible.','error');});return writeQueue;}
function migrateLegacy(){try{const old=JSON.parse(localStorage.getItem('classe_batonnets')||'null');if(!Array.isArray(old)||!old.length||!old.every(x=>x&&typeof x.name==='string'))return null;const state=makeState();const y=yrFor(state);y.students=old.map(s=>({id:uid(),name:String(s.name).slice(0,100),active:true,addedOn:today()}));y.round=y.students.filter((s,i)=>old[i]?.picked).map(s=>s.id);ensureMigrationNote();return state;}catch(e){return null}}
const yrFor=state=>state.years[0];
function ensureMigrationNote(){try{sessionStorage.setItem('pot-magique-migrated','1')}catch(e){}}
function normalizeState(state){if(!state||state.version!==2||!Array.isArray(state.years)||!state.years.length)throw new Error('Format de sauvegarde incompatible');for(const y of state.years){if(!Array.isArray(y.students)||!Array.isArray(y.events)||!y.attendance||!Array.isArray(y.layouts))throw new Error('Sauvegarde incomplète');y.round=Array.isArray(y.round)?y.round:[];y.classDays=Array.isArray(y.classDays)?y.classDays:Object.keys(y.attendance);y.questions=Array.isArray(y.questions)?y.questions:[];y.observations=Array.isArray(y.observations)?y.observations:[];if(!y.layouts.length){const l=initialLayout();y.layouts=[l];y.activeLayoutId=l.id;}if(!y.layouts.some(l=>l.id===y.activeLayoutId))y.activeLayoutId=y.layouts[0].id;}
 state.activeYearId=state.years.some(y=>y.id===state.activeYearId)?state.activeYearId:state.years[0].id;state.preferences={confetti:true,reducedMotion:false,...state.preferences};if(!VISUALS.some(v=>v.id===state.visual))state.visual='sticks';if(!['random','fair'].includes(state.mode))state.mode='random';state.subject=typeof state.subject==='string'?state.subject:'';state.askQuestion=!!state.askQuestion;return state;}
function toast(message,type='success'){const root=$('#toastRoot');if(!root)return;root.innerHTML=`<div class="toast ${type==='error'?'error':''}" role="status">${esc(message)}</div>`;clearTimeout(UI.toastTimer);UI.toastTimer=setTimeout(()=>root.innerHTML='',3400)}
function modal(title,body,actions=''){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop" data-action="modal-backdrop"><section class="modal-panel" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-top"><h2>${esc(title)}</h2><button class="modal-close" data-action="close-modal" aria-label="Fermer">${ic('close')}</button></div><div>${body}</div>${actions}</section></div>`;$('.modal-close',root)?.focus()}
function closeModal(){$('#modalRoot').innerHTML=''}
function confirmDialog(title,body,yes,opts={}){modal(title,`<p>${esc(body)}</p>`,`<div class="modal-actions"><button class="btn btn-outline" data-action="close-modal">Annuler</button><button class="btn ${opts.danger?'btn-danger':'btn-primary'}" id="modalConfirm">${esc(opts.label||'Confirmer')}</button></div>`);$('#modalConfirm').addEventListener('click',()=>{closeModal();yes()},{once:true});}
function downloadBlob(name,contents,type){const blob=new Blob([contents],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportJSON(){downloadBlob(`pot-magique-sauvegarde-${today()}.json`,JSON.stringify(S,null,2),'application/json;charset=utf-8');toast('Sauvegarde JSON téléchargée.');}
function exportCSV(){const y=yr(),header=['Date','Heure','Élève','Matière','Mode','Animation','Question'],rows=y.events.slice().sort((a,b)=>a.at.localeCompare(b.at)).map(e=>[e.at.slice(0,10),new Date(e.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),y.students.find(s=>s.id===e.studentId)?.name||'Élève archivé',e.subject||'Sans matière',e.mode==='fair'?'Équitable':'Aléatoire',VISUALS.find(v=>v.id===e.visual)?.name||e.visual,e.questionText||'']);const csv=[header,...rows].map(row=>row.map(v=>{const text=String(v??'');const safe=/^[=+@\-\t\r]/.test(text)?"'"+text:text;return '"'+safe.replaceAll('"','""')+'"'}).join(';')).join('\r\n');downloadBlob(`pot-magique-${y.label}-interrogations.csv`,'\ufeff'+csv,'text/csv;charset=utf-8');toast('Historique CSV téléchargé.');}
function exportStatsCSV(){const stats=getStats(),bounds=periodBounds(),y=yr();const csvRow=values=>values.map(value=>{const original=String(value??'');const safe=/^[=+@\-\t\r]/.test(original)?"'"+original:original;return '"'+safe.replaceAll('"','""')+'"'}).join(';');const header=['Élève','Interrogations','Part des interrogations (%)','Jours de présence enregistrés','Interrogations par jour présent','Début','Fin','Matière'];const rows=y.students.filter(s=>s.active||stats.counts.get(s.id)||stats.presence.get(s.id)).sort((a,b)=>a.name.localeCompare(b.name,'fr')).map(student=>{const count=stats.counts.get(student.id)||0,present=stats.presence.get(student.id)||0;return [student.name,count,stats.total?(100*count/stats.total).toFixed(2):0,present,present?(count/present).toFixed(2):0,bounds.start,bounds.end,UI.statsSubject||'Toutes']});rows.push([]);rows.push(['TOTAL CLASSE',stats.total,stats.total?100:0,'','','','','']);rows.push(['ÉLÈVES DIFFÉRENTS',stats.uniqueStudents.size]);rows.push(['COUVERTURE CLASSE (%)',stats.coverage.toFixed(2)]);downloadBlob(`pot-magique-${y.label}-statistiques-${UI.statsPeriod}.csv`,'\ufeff'+[header,...rows].map(csvRow).join('\r\n'),'text/csv;charset=utf-8');toast('Statistiques CSV téléchargées, prêtes pour Excel.');}
const pageName={tirage:'Tirage au sort',stats:'Statistiques',students:'Mes élèves',layout:'Plan de classe',history:'Historique',questions:'Mes questions',settings:'Paramètres'};
function renderChrome(){const select=$('#globalYearSelect');if(select)select.innerHTML=S.years.map(y=>`<option value="${esc(y.id)}" ${y.id===S.activeYearId?'selected':''}>${esc(y.label)}</option>`).join('');$('#todayLabel').textContent=new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});$$('[data-page].nav-item').forEach(e=>{e.classList.toggle('active',e.dataset.page===UI.page);e.setAttribute('aria-current',e.dataset.page===UI.page?'page':'false')})}
function pageHeading(eyebrow,title,subtitle,actions=''){return `<div class="page-heading"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${title}</h1><p class="page-subtitle">${subtitle}</p></div>${actions?`<div class="heading-actions">${actions}</div>`:''}</div>`}
function render(){renderChrome();const pages={tirage:renderDraw,stats:renderStats,students:renderStudents,layout:renderLayout,history:renderHistory,questions:renderQuestions,settings:renderSettings};$('#pageContent').innerHTML=(pages[UI.page]||renderDraw)();if(UI.page==='tirage'&&S.visual==='wheel')paintWheel();if(UI.page==='tirage'&&UI.pending&&!UI.animating)showReveal();if(UI.page==='layout')setupBoardDnD();renderProjector();}
function goPage(name){if(UI.animating){toast('Terminez d’abord le tirage en cours.');return;}if(UI.pending){toast('Confirmez ou annulez le tirage avant de changer de page.');return;}UI.page=name;closeModal();$('#sidebar').classList.remove('open');$('.mobile-dim')?.remove();render();$('#pageContent').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function changeYear(id){if(!S.years.some(y=>y.id===id))return;if(UI.pending||UI.animating){toast('Terminez le tirage en cours.');renderChrome();return;}S.activeYearId=id;UI.selectedStudentId='';UI.selectedLayoutItemId='';UI.lastResult=null;UI.calendarSelected=today();UI.calendarMonth=today().slice(0,7)+'-01';save();render();}
/* ───────────────────────────── Tirage ───────────────────────────── */
function renderDraw(){const y=yr(),available=getEligible(),absent=activeStudents().filter(s=>isAbsent(s.id)).length,drawn=activeStudents().filter(s=>y.round.includes(s.id)).length;
 const actions=`<button class="btn btn-outline" data-action="projector">${ic('eye')} Mode classe</button>`;
 return `${pageHeading('LE HASARD A DU BON','À qui le tour ? ✨','Un prénom, un sourire, une chance de participer. À toi de jouer !',actions)}
 <div class="draw-toolbar"><div class="draw-type-list" aria-label="Animation du tirage">${VISUALS.map(v=>`<button class="draw-type ${v.id===S.visual?'active':''}" data-action="visual" data-visual="${v.id}" aria-pressed="${v.id===S.visual}"><span class="draw-type-emoji">${v.emoji}</span>${v.name}</button>`).join('')}</div><span class="chip sage">✦ ${available.length} ${available.length===1?'élève disponible':'élèves disponibles'} ${help('eligible')}</span></div>
 <div class="draw-layout"><section class="card draw-stage-card"><div class="stage-topline"><span class="icon-text">✦ ${esc(VISUALS.find(v=>v.id===S.visual).name.toUpperCase())}</span><span>${esc(y.label)} · ${activeStudents().length} élèves</span></div><div class="draw-stage" id="drawStage"><div class="stage-halo"></div><span class="stage-spark one">✦</span><span class="stage-spark two">✧</span><span class="stage-spark three">✳</span><span class="stage-spark four">✦</span>${drawVisual(available)}<div class="draw-result" id="drawReveal" aria-live="polite"></div></div><div class="stage-actions"><button id="mainDrawButton" data-action="draw" class="btn btn-primary btn-large glow" ${!available.length||UI.animating||UI.pending?'disabled':''}>${ic('wand','icon-lg')} Tirer au sort ✨</button><button class="btn btn-outline" data-action="reset-round" ${!y.round.length?'disabled':''}>${ic('rotate')} Nouveau tour</button></div><p id="stageStatus" class="stage-caption">${available.length?'Chaque tirage peut être confirmé ou annulé.':(!activeStudents().length?'Ajoutez des prénoms dans Paramètres pour commencer.':absent===activeStudents().length?'Tous les élèves sont absents.':'Tout le monde est passé ! Lancez un nouveau tour.')}</p>${!activeStudents().length?'<button class="btn btn-soft" data-action="settings-class">⚙️ Ajouter les prénoms dans Paramètres</button>':''}</section>
 <aside class="stack"><section class="card draw-controls-card"><div class="card-title">⚙️ Paramètres du tirage ${help('random')}</div><div class="control-block"><div class="control-label">Comment choisir l'élève ?</div><div class="mode-options"><button data-action="mode" data-mode="random" class="mode-card ${S.mode==='random'?'active':''}" aria-pressed="${S.mode==='random'}"><span class="mode-icon">🎲</span><strong>100 % aléatoire</strong><small>Mêmes chances pour tous</small></button><button data-action="mode" data-mode="fair" class="mode-card ${S.mode==='fair'?'active':''}" aria-pressed="${S.mode==='fair'}"><span class="mode-icon">⚖️</span><strong>Équitable</strong><small>Favorise les moins interrogés</small></button></div><div class="mode-panel"><strong>${S.mode==='random'?'🎲 Le hasard pur':'⚖️ L’équité sur 20 jours'} ${help(S.mode)}</strong><br>${S.mode==='random'?'Tous les élèves disponibles ont la même probabilité.':'Les chances tiennent compte des interrogations et des présences enregistrées.'}${S.mode==='fair'?` <button class="help-dot" data-action="probabilities" title="Voir les probabilités" aria-label="Voir les probabilités">%</button>`:''}</div></div><div class="control-row"><div class="control-block"><label class="control-label" for="drawSubject">Matière ${help('subject')}</label><select class="field" id="drawSubject">${subjectOptions(S.subject||'Sans matière')}</select></div><div class="control-block"><label class="toggle"><input id="questionToggle" type="checkbox" ${S.askQuestion?'checked':''}> Tirer aussi une question</label><p class="inline-help">Depuis votre banque de questions, dans la matière choisie.</p></div></div></section>
 <section class="card"><div class="card-head"><div class="card-title">📋 Ma classe</div><span class="chip sage">${available.length} restants</span></div><div class="tiny-row muted small mb-2"><span>✅ ${drawn} passés</span><span>○ ${absent} absents</span><span>${activeStudents().length} au total</span></div><div class="roster-list">${y.students.filter(s=>s.active).map((s,i)=>`<div class="roster-row ${y.round.includes(s.id)?'is-drawn':''} ${isAbsent(s.id)?'is-absent':''}"><div class="roster-left"><span class="roster-avatar" style="--avatar-bg:${avatarColor(i)}">${esc(s.name.slice(0,1).toUpperCase())}</span><span class="roster-name" title="${esc(s.name)}">${esc(s.name)} ${y.round.includes(s.id)?'✓':''}</span></div><button class="roster-btn ${isAbsent(s.id)?'absent':''}" data-action="toggle-absence" data-id="${esc(s.id)}" title="${isAbsent(s.id)?'Marquer présent':'Marquer absent'}">${isAbsent(s.id)?'Absent · ↻':'Présent · ✓'}</button></div>`).join('')||'<div class="empty">Ajoutez les prénoms dans Paramètres pour commencer.</div>'}</div></section></aside></div>
 ${UI.lastResult?`<div class="last-result"><span>🌟 Dernier tirage confirmé : <strong>${esc(UI.lastResult.name)}</strong> · ${esc(UI.lastResult.subject)}</span><button class="btn btn-small btn-outline" data-action="undo-last">${ic('rotate')} Annuler ce tirage</button></div>`:''}`;
}
function drawVisual(available){switch(S.visual){
 case 'sticks':case 'pencils':return renderJar(available);
 case 'wheel':return `<div class="wheel-scene"><span class="wheel-pointer"></span><div class="wheel-disc"><canvas class="wheel-canvas" width="640" height="640" aria-label="Roue contenant ${available.length} prénoms"></canvas></div><div class="wheel-hub">✦</div></div>`;
 case 'cards':return `<div class="card-scene">${Array.from({length:Math.min(available.length,16)},(_,i)=>`<button class="mystery-card" type="button" data-action="draw" title="Tirer une carte mystère" style="--card-color:${pastelFor(i)};--tilt:${((i%5)-2)*3}deg;--delay:${(i%7)*-0.06}s"><span>✦</span></button>`).join('')||'<span class="muted">Aucune carte restante</span>'}</div>`;
 case 'balls':return `<div class="ball-scene"><div class="ball-machine">${Array.from({length:Math.min(available.length,30)},(_,i)=>`<span class="lottery-ball" style="--ball-color:${pastelFor(i)};--bx:${14+(i%5)*40}px;--by:${17+Math.floor(i/5)*30}px;--dx:${(i*37%97)-48}px;--dy:${(i*61%91)-45}px;--delay:${(i%7)*-0.13}s" title="${esc(available[i].name)}">${esc(available[i].name.slice(0,2).toUpperCase())}</span>`).join('')}</div><div class="ball-chute"></div><div class="ball-machine-base"></div></div>`;
 default:return ''}}
function renderJar(available){const pencil=S.visual==='pencils',shown=available.slice(0,Math.min(available.length,36));return `<div class="jar-scene"><span class="jar-shadow"></span><div class="${pencil?'pencil-bunch':'stick-bunch'}">${shown.map((s,i)=>{const angle=-31+(i/Math.max(1,shown.length-1))*62+Math.sin(i*9)*3;return `<div class="${pencil?'mini-pencil':'mini-stick'}" data-token-id="${esc(s.id)}" style="--angle:${angle}deg;--delay:${(i%7)*-0.06}s;transform:translateX(${(i%3-1)*1.6}px) rotate(${angle}deg);${pencil?`--pencil:${pastelFor(i)};`:''}z-index:${i}"><span class="stick-letters">${esc(s.name)}</span></div>`}).join('')}</div><div class="jar"></div></div>`;}
function paintWheel(){for(const canvas of $$('.wheel-canvas')){const ctx=canvas.getContext('2d');if(!ctx)return;const available=getEligible(),count=Math.max(1,available.length),center=320,r=306;ctx.clearRect(0,0,640,640);for(let i=0;i<count;i++){const start=-Math.PI/2+i*2*Math.PI/count,end=start+2*Math.PI/count;ctx.beginPath();ctx.moveTo(center,center);ctx.arc(center,center,r,start,end);ctx.closePath();ctx.fillStyle=PASTEL_COLORS[i%PASTEL_COLORS.length];ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fffaf0';ctx.stroke();if(!available.length)continue;ctx.save();ctx.translate(center,center);ctx.rotate(start+Math.PI/count);ctx.fillStyle='#536758';ctx.font=`700 ${count>23?12:count>15?15:count>8?19:25}px DM Sans, sans-serif`;ctx.textAlign='right';ctx.textBaseline='middle';let name=available[i].name;if(name.length>(count>18?12:18))name=name.slice(0,count>18?10:15)+'…';ctx.fillText(name,r-19,0,Math.max(88,r*.65));ctx.restore();}ctx.beginPath();ctx.arc(center,center,22,0,2*Math.PI);ctx.fillStyle='#fff';ctx.fill();}}
function drawWheelTo(chosen,available){const index=available.findIndex(s=>s.id===chosen.id),step=360/available.length;$$('.wheel-disc').forEach(wheel=>{const current=Number(wheel.dataset.rotation||'0'),currentNorm=((current%360)+360)%360,targetNorm=((-(index+.5)*step)%360+360)%360,advance=(targetNorm-currentNorm+360)%360,final=current+360*5+advance;wheel.dataset.rotation=final;wheel.style.transform=`rotate(${final}deg)`;});}
function animateDrawScene(chosen,reduced){$$('.draw-stage').forEach(stage=>{stage.classList.add('is-drawing',`drawing-${S.visual}`);if(reduced)return;const token=$$('[data-token-id]',stage).find(el=>el.dataset.tokenId===chosen.id);if(token)token.classList.add('chosen-token');if(S.visual==='cards'){const cards=$$('.mystery-card',stage);if(cards.length)cards[Math.floor(rand()*cards.length)].classList.add('selected');}});}
function revealObject(chosen,reduced){if(reduced||S.visual==='wheel')return;$$('.draw-stage').forEach(stage=>{const prop=document.createElement('div');prop.className=`drawn-prop prop-${S.visual}`;prop.textContent=chosen.name;prop.setAttribute('aria-hidden','true');stage.appendChild(prop);});}
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function startDraw(){if(UI.animating||UI.pending)return;let eligible=getEligible();if(!eligible.length){toast('Aucun élève disponible : ajoutez des prénoms, vérifiez les absences ou recommencez le tour.','error');return;}ensureAttendanceDay();eligible=getEligible();const chosen=pickCandidate();if(!chosen)return;const qMatches=yr().questions.filter(q=>S.subject==='Sans matière'||!S.subject||q.subject===S.subject),question=S.askQuestion&&qMatches.length?pickUniform(qMatches):null;if(S.askQuestion&&!qMatches.length)toast('Pas de question pour cette matière : tirage du prénom uniquement.');UI.pending={studentId:chosen.id,name:chosen.name,visual:S.visual,mode:S.mode,subject:S.subject||'Sans matière',questionText:question?.text||'',questionId:question?.id||null};UI.animating=true;save();const btn=$('#mainDrawButton');if(btn)btn.disabled=true;const reduced=S.preferences.reducedMotion||window.matchMedia?.('(prefers-reduced-motion: reduce)').matches,duration=reduced?100:({wheel:3900,cards:2200,balls:2700,pencils:2400,sticks:2400}[S.visual]||2400);if(UI.projector){renderProjector();if(S.visual==='wheel')paintWheel();}animateDrawScene(chosen,reduced);if(S.visual==='wheel'&&!reduced)drawWheelTo(chosen,eligible);
 const ticker=$('#stageStatus'),previewNames=eligible.map(s=>s.name),started=Date.now();let unveiled=false;while(Date.now()-started<duration){const elapsed=Date.now()-started;if(!unveiled&&elapsed>=duration*.57){revealObject(chosen,reduced);unveiled=true;}if(S.visual!=='wheel'&&elapsed<duration*.55){const name=pickUniform(previewNames);if(ticker)ticker.textContent=`✨ ${name}…`;if(UI.projector){const p=$('#projectorName');if(p)p.textContent='✨ '+name+'…';}}await delay(reduced?100:80);}UI.animating=false;if(ticker)ticker.textContent='Vérifiez que cet élève a bien été interrogé, puis confirmez.';showReveal();renderProjector();if(S.preferences.confetti)launchConfetti();}
function showReveal(){const pending=UI.pending;if(!pending)return;const el=$('#drawReveal');if(!el)return;el.innerHTML=`<div class="result-sparkle">🌟</div><div class="result-kicker">Le sort a choisi…</div><h2>${esc(pending.name)}</h2><span class="chip sage">${esc(pending.subject)}</span>${pending.questionText?`<div class="result-question">📖 ${esc(pending.questionText)}</div>`:''}<div class="result-buttons"><button class="btn btn-primary" data-action="confirm-draw">${ic('check')} Interrogation effectuée</button><button class="btn btn-outline" data-action="cancel-draw">Annuler ce tirage</button></div>`;el.classList.add('visible');}
function confirmDraw(){if(!UI.pending||UI.animating)return;const p=UI.pending,y=yr();const event={id:uid(),studentId:p.studentId,at:new Date().toISOString(),day:today(),subject:p.subject,mode:p.mode,visual:p.visual,questionText:p.questionText,questionId:p.questionId};y.events.push(event);if(!y.round.includes(p.studentId))y.round.push(p.studentId);UI.lastResult={name:p.name,studentId:p.studentId,subject:p.subject,at:event.at,id:event.id};UI.pending=null;save();toast(`${p.name} : interrogation enregistrée !`);render();}
function cancelDraw(){if(!UI.pending||UI.animating)return;const name=UI.pending.name;UI.pending=null;toast(`Tirage de ${name} annulé : aucune interrogation comptabilisée.`);render();}
function resetRound(){if(UI.pending||UI.animating)return;if(!yr().round.length)return;yr().round=[];save();toast('Nouveau tour ! Les statistiques sont conservées.');render();}
function toggleAbsent(id,date=today()){if(UI.pending||UI.animating){toast('Terminez le tirage en cours avant de modifier les absences.');return;}const s=studentById(id);if(!s)return;ensureAttendanceDay(date);const record=yr().attendance[date];record[id]=record[id]==='absent'?'present':'absent';save();toast(`${s.name} : ${record[id]==='absent'?'absent':'présent'} le ${fmtDate(date,{day:'numeric',month:'long'})}.`);render();}
function undoLast(){const y=yr();const event=UI.lastResult&&y.events.find(e=>e.id===UI.lastResult.id);if(!event){toast('Aucun dernier tirage à annuler.');return;}confirmDialog('Annuler l’interrogation',`Retirer l’interrogation de ${studentById(event.studentId)?.name||'cet élève'} ? Les statistiques seront recalculées.`,()=>{y.events=y.events.filter(e=>e.id!==event.id);y.round=y.round.filter(id=>id!==event.studentId);UI.lastResult=null;save();render();toast('Interrogation retirée.');},{danger:true,label:'Supprimer le tirage'});}
function showProbabilities(){const eligible=getEligible();const rows=S.mode==='random'?eligible.map(s=>({person:s,rate:0,presentDays:0,count:0,probability:100/eligible.length})):equityData(eligible);modal('Chances au prochain tirage',`<p>Calcul sur les ${Math.min(20,rateWindowDays().length)} derniers jours de classe enregistrés. Les probabilités changent après chaque interrogation confirmée et chaque mise à jour de présence. ${help('probability')}</p><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Élève</th><th>Interrogations</th><th>Jours présents</th><th>Chances</th></tr></thead><tbody>${rows.sort((a,b)=>b.probability-a.probability).map(r=>`<tr><td><strong>${esc(r.person.name)}</strong></td><td>${r.count}</td><td>${r.presentDays}</td><td><strong>${fmtPct(r.probability)}</strong></td></tr>`).join('')||'<tr><td colspan="4">Aucun élève éligible.</td></tr>'}</tbody></table></div><div class="notice mt-2"><strong>Mode ${S.mode==='fair'?'équitable':'aléatoire'}</strong> — ${esc(HELP[S.mode].body)}</div>`);}
/* Confettis : version autonome de l'animation du prototype. */
function launchConfetti(){if(S.preferences.reducedMotion)return;const canvas=$('#confettiCanvas'),ctx=canvas?.getContext('2d');if(!ctx)return;canvas.width=innerWidth;canvas.height=innerHeight;const colors=PASTEL_COLORS;let particles=Array.from({length:56},()=>({x:canvas.width/2,y:canvas.height*.38,vx:(rand()-.5)*15,vy:(rand()-.7)*16,size:4+rand()*7,rot:rand()*360,vrot:(rand()-.5)*14,color:pickUniform(colors)}));let frame=0;function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.38;p.rot+=p.vrot;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);ctx.fillStyle=p.color;ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size);ctx.restore()});if(++frame<85)requestAnimationFrame(animate);else ctx.clearRect(0,0,canvas.width,canvas.height);}requestAnimationFrame(animate);}
function renderProjector(){const root=$('#projectorRoot');if(!UI.projector){root.innerHTML='';return;}const p=UI.pending,last=UI.lastResult;let shown=UI.animating?'Le suspense…':p?p.name:last?.name||'Qui sera tiré ?';root.innerHTML=`<div class="projector"><div class="projector-top"><span class="projector-title">✏️ Le Pot Magique</span><button class="btn btn-outline btn-small" data-action="projector-close">${ic('close')} Quitter le mode classe</button></div><div class="projector-center"><div class="projector-stage draw-stage">${drawVisual(getEligible())}</div><div class="projector-kicker">${p&&!UI.animating?'LE PRÉNOM EST…':'LE TIRAGE AU SORT'}</div><div id="projectorName" class="projector-name">${esc(shown)}</div>${p?.questionText&&!UI.animating?`<div class="projector-question">📖 ${esc(p.questionText)}</div>`:''}<div class="projector-actions">${p&&!UI.animating?`<button class="btn btn-primary" data-action="confirm-draw">${ic('check')} Confirmer</button><button class="btn btn-outline" data-action="cancel-draw">Annuler</button>`:`<button class="btn btn-primary btn-large" data-action="draw" ${UI.animating||!getEligible().length?'disabled':''}>✨ Tirer un élève</button>`}</div></div><div class="projector-foot">Tous les élèves ont leur chance ♡ · Aucune donnée individuelle affichée</div></div>`;if(S.visual==='wheel')paintWheel();}
function enterProjector(){UI.projector=true;renderProjector();if(S.visual==='wheel')paintWheel();document.documentElement.requestFullscreen?.().catch(()=>{});}
function exitProjector(){UI.projector=false;renderProjector();if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});render();}
/* ───────────────────── Statistiques et fiches ───────────────────── */
const eventDay=e=>e.day||isoDay(new Date(e.at));
function periodBounds(period=UI.statsPeriod){const d=today();if(period==='today')return {start:d,end:d};if(period==='week'){const start=startOfWeek(d),end=dateObj(start);end.setDate(end.getDate()+6);return {start,end:isoDay(end)};}if(period==='month'){const now=new Date();return {start:isoDay(new Date(now.getFullYear(),now.getMonth(),1)),end:isoDay(new Date(now.getFullYear(),now.getMonth()+1,0))};}if(period==='year'){const match=yr().label.match(/^\d{4}/),first=match?Number(match[0]):new Date().getFullYear();return {start:`${first}-08-01`,end:`${first+1}-07-31`};}return {start:UI.statsFrom||today(),end:UI.statsTo||today()};}
function filteredEvents(period=UI.statsPeriod,subject=UI.statsSubject){const {start,end}=periodBounds(period);return yr().events.filter(e=>{const d=eventDay(e);return d>=start&&d<=end&&(!subject||e.subject===subject)});}
function attendanceDates(period=UI.statsPeriod){const {start,end}=periodBounds(period);return yr().classDays.filter(d=>d>=start&&d<=end).sort();}
function getStats(period=UI.statsPeriod,subject=UI.statsSubject){const events=filteredEvents(period,subject),days=attendanceDates(period),presentStudents=new Set();days.forEach(d=>Object.entries(yr().attendance[d]||{}).forEach(([id,status])=>{if(status==='present')presentStudents.add(id);}));const counts=new Map(),presence=new Map();yr().students.forEach(s=>{counts.set(s.id,events.filter(e=>e.studentId===s.id).length);presence.set(s.id,days.filter(d=>yr().attendance[d]?.[s.id]==='present').length)});const uniqueStudents=new Set(events.map(e=>e.studentId));const coverage=presentStudents.size?100*[...uniqueStudents].filter(id=>presentStudents.has(id)).length/presentStudents.size:0;return {events,days,counts,presence,uniqueStudents,presentStudents,coverage,total:events.length};}
function statCard(label,number,foot,flavor,tooltip){return `<div class="stat-card ${flavor}"><div class="stat-label">${label} ${tooltip?help(tooltip):''}</div><div class="stat-number">${esc(number)}</div><div class="stat-foot">${foot}</div></div>`;}
function chartBuckets(st){const {start,end}=periodBounds();const countFor=(from,to)=>st.events.filter(e=>eventDay(e)>=from&&eventDay(e)<=to).length;let buckets=[];if(UI.statsPeriod==='today'){for(let h=7;h<=20;h++)buckets.push({label:`${h} h`,value:st.events.filter(e=>new Date(e.at).getHours()===h).length});const outside=st.events.filter(e=>{const h=new Date(e.at).getHours();return h<7||h>20}).length;if(outside)buckets.push({label:'Autres',value:outside});return buckets;}if(UI.statsPeriod==='week'){let d=dateObj(start);for(let i=0;i<7;i++){const iso=isoDay(d);buckets.push({label:['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'][i],value:countFor(iso,iso)});d.setDate(d.getDate()+1);}return buckets;}if(UI.statsPeriod==='month'){const first=dateObj(start);for(let day=1;day<=31;day+=7){const from=isoDay(new Date(first.getFullYear(),first.getMonth(),day)),to=isoDay(new Date(first.getFullYear(),first.getMonth(),Math.min(day+6,new Date(first.getFullYear(),first.getMonth()+1,0).getDate())));if(from<=end)buckets.push({label:`${day}-${Math.min(day+6,new Date(first.getFullYear(),first.getMonth()+1,0).getDate())}`,value:countFor(from,to)});}return buckets;}if(UI.statsPeriod==='year'){const base=dateObj(start);for(let i=0;i<12;i++){const from=isoDay(new Date(base.getFullYear(),base.getMonth()+i,1)),to=isoDay(new Date(base.getFullYear(),base.getMonth()+i+1,0));buckets.push({label:dateObj(from).toLocaleDateString('fr-FR',{month:'short'}),value:countFor(from,to)})}return buckets;}const days=Math.floor((dateObj(end)-dateObj(start))/86400000)+1;let cursor=dateObj(start);const step=days>60?30:days>20?7:1;while(isoDay(cursor)<=end&&buckets.length<20){const from=isoDay(cursor);cursor.setDate(cursor.getDate()+step-1);const to=isoDay(cursor)>end?end:isoDay(cursor);buckets.push({label:step===1?fmtDate(from,{day:'numeric',month:'short'}):fmtDate(from,{day:'numeric',month:'short'}),value:countFor(from,to)});cursor.setDate(cursor.getDate()+1)}return buckets;}
function barChart(buckets){const max=Math.max(1,...buckets.map(b=>b.value));return `<div class="chart-bars" role="img" aria-label="Interrogations par période : ${esc(buckets.map(b=>b.label+' : '+b.value).join(', '))}">${buckets.map(b=>`<div class="chart-slot"><div class="chart-value">${b.value||''}</div><div class="chart-bar" style="height:${Math.max(2,b.value/max*82)}%" title="${b.value} interrogations"></div><div class="chart-label">${esc(b.label)}</div></div>`).join('')}</div>`;}
function renderStats(){const st=getStats();const studentOptions=yr().students.filter(s=>s.active).map(s=>`<option value="${esc(s.id)}" ${s.id===UI.selectedStudentId?'selected':''}>${esc(s.name)}</option>`).join('');if(!studentById(UI.selectedStudentId))UI.selectedStudentId=activeStudents()[0]?.id||'';
 const counts=yr().students.filter(s=>s.active).map(s=>({person:s,count:st.counts.get(s.id)||0,present:st.presence.get(s.id)||0,share:st.total?100*(st.counts.get(s.id)||0)/st.total:0,rate:(st.counts.get(s.id)||0)/Math.max(1,st.presence.get(s.id)||0)})).sort((a,b)=>a.person.name.localeCompare(b.person.name,'fr'));
 const presentToday=activeStudents().filter(s=>!isAbsent(s.id)).length;
 return `${pageHeading('VOTRE TABLEAU DE BORD','La participation en un clin d’œil 📊','Des données claires pour accompagner chaque élève à son rythme.',`<button class="btn btn-outline" data-action="export-stats-csv">${ic('download')} Exporter les statistiques CSV</button>`)}
 <div class="card mb-2"><div class="filter-row"><label><span class="control-label">Période</span><select class="field" id="statsPeriod"><option value="today" ${UI.statsPeriod==='today'?'selected':''}>Aujourd’hui</option><option value="week" ${UI.statsPeriod==='week'?'selected':''}>Cette semaine</option><option value="month" ${UI.statsPeriod==='month'?'selected':''}>Ce mois-ci</option><option value="year" ${UI.statsPeriod==='year'?'selected':''}>Année scolaire</option><option value="custom" ${UI.statsPeriod==='custom'?'selected':''}>Personnalisée</option></select></label><label><span class="control-label">Matière ${help('subject')}</span><select class="field" id="statsSubject">${subjectOptions(UI.statsSubject,true)}</select></label>${UI.statsPeriod==='custom'?`<label><span class="control-label">Du</span><input type="date" class="field" id="statsFrom" value="${UI.statsFrom}" /></label><label><span class="control-label">Au</span><input type="date" class="field" id="statsTo" value="${UI.statsTo}" /></label>`:''}</div><div class="inline-help mt-1">${fmtDate(periodBounds().start)} → ${fmtDate(periodBounds().end)} · ${st.days.length} journées enregistrées ${help('attendance')}</div></div>
 <div class="stats-cards mb-2">${statCard('Interrogations',fmtInt(st.total),'Confirmées sur la période','sage','times')}${statCard('Élèves interrogés',fmtInt(st.uniqueStudents.size),'Élèves différents','lav')}${statCard('Couverture',fmtPct(st.coverage),`${st.presentStudents.size} élèves présents au moins une fois`,'peach','coverage')}${statCard('Présents aujourd’hui',`${presentToday}/${activeStudents().length}`,'Absences du jour','rose','attendance')}</div>
 <div class="page-grid stats-grid"><div class="stack"><section class="card"><div class="card-head"><h3>📈 Évolution des interrogations</h3><span class="chip sage">${fmtInt(st.total)} au total</span></div>${barChart(chartBuckets(st))}<p class="inline-help">Seules les interrogations confirmées sont comptabilisées. ${help('times')}</p></section>
 <section class="card"><div class="card-head"><h3>Participation par élève ${help('equity')}</h3><span class="chip lav">${counts.length} élèves actifs</span></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Élève</th><th>Interrogations ${help('times')}</th><th>Part ${help('share')}</th><th>Présences</th><th>Par jour présent ${help('presenceRate')}</th></tr></thead><tbody>${counts.map((r,i)=>`<tr><td><strong>${esc(r.person.name)}</strong></td><td>${r.count}</td><td>${fmtPct(r.share)}</td><td>${r.present} j</td><td>${fmtRate(r.rate)}</td></tr>`).join('')||'<tr><td colspan="5">Ajoutez des élèves pour commencer.</td></tr>'}</tbody></table></div></section></div>
 <div class="stack"><section class="card"><div class="card-head"><h3>🌱 Part de participation ${help('share')}</h3></div><div class="list-lines">${counts.filter(r=>r.count>0).sort((a,b)=>b.count-a.count).slice(0,10).map(r=>`<div class="stat-progress"><span class="progress-name" title="${esc(r.person.name)}">${esc(r.person.name)}</span><span class="progress-track"><span class="progress-fill" style="display:block;width:${r.share}%"></span></span><span class="number">${fmtPct(r.share)}</span></div>`).join('')||'<p class="muted">Les premiers graphiques apparaîtront après les interrogations.</p>'}</div></section>
 <section class="card"><div class="card-head"><h3>👤 Fiche individuelle</h3></div><label class="control-label" for="statsStudent">Choisir un élève</label><select class="field" id="statsStudent">${studentOptions}</select>${profileHTML(UI.selectedStudentId,st,false)}</section>
 <div class="notice"><strong>💡 Bon à savoir</strong><br>Les pourcentages indiquent ce qui s’est passé, pas les chances du prochain tirage. Pour connaître celles-ci, ouvrez « Tirage au sort » puis « Mode équitable ».</div></div></div>`;}
function profileHTML(id,st=getStats(),showNotes=true){const s=studentById(id);if(!s)return '<div class="empty">Choisissez un élève pour voir sa fiche.</div>';const n=st.counts.get(id)||0,p=st.presence.get(id)||0,share=st.total?100*n/st.total:0;const obs=yr().observations.filter(o=>o.studentId===id).sort((a,b)=>b.at.localeCompare(a.at));return `<div class="profile-panel"><div class="profile-head"><span class="person-avatar" style="--avatar-bg:#e6dbee">${esc(s.name.slice(0,1).toUpperCase())}</span><div><h3>${esc(s.name)}</h3><span class="small muted">${s.active?'Élève actif':'Élève archivé'} · ${isAbsent(id)?'Absent aujourd’hui':'Présent aujourd’hui'}</span></div></div><div class="profile-stats"><div class="mini-stat"><strong>${n}</strong><span>Interrogations ${help('times')}</span></div><div class="mini-stat"><strong>${fmtPct(share)}</strong><span>Part de classe ${help('share')}</span></div><div class="mini-stat"><strong>${fmtRate(n/Math.max(1,p))}</strong><span>Par jour présent ${help('presenceRate')}</span></div></div><p class="inline-help">${p} journées de présence enregistrées pendant la période sélectionnée.</p>${showNotes?`<h4 class="mt-2">📝 Observations privées</h4>${obs.slice(0,5).map(o=>`<div class="obs-item"><strong>${esc(o.label)} · ${fmtDate(eventDay(o),{day:'numeric',month:'short'})}</strong><p>${esc(o.text||'Sans commentaire')}${o.subject?` · ${esc(o.subject)}`:''}</p></div>`).join('')||'<p class="small muted">Aucune observation pour le moment.</p>'}<button class="btn btn-lav btn-small mt-1" data-action="new-observation" data-id="${esc(id)}">${ic('plus')} Ajouter une observation</button>`:''}</div>`;}
/* ─────────────────────────── Élèves ─────────────────────────── */
function renderStudents(){const y=yr(),term=UI.studentFilter.trim().toLocaleLowerCase('fr'),students=y.students.filter(s=>s.name.toLocaleLowerCase('fr').includes(term)).sort((a,b)=>a.name.localeCompare(b.name,'fr'));const selected=studentById(UI.selectedStudentId);return `${pageHeading('MON PETIT MONDE','Tous mes élèves 🌼','Retrouvez les prénoms, gérez les absences et notez les progrès de chacun.',`<span class="chip sage">${activeStudents().length} élèves actifs</span>`)}
 <div class="page-grid"><div class="stack"><section class="card"><div class="card-head"><h3>🧸 Liste de la classe</h3><span class="chip peach">${activeStudents().filter(s=>isAbsent(s.id)).length} absent(s)</span></div><div class="field-row mb-2"><label class="field-grow"><span class="control-label">Rechercher un prénom</span><input class="field" id="studentFilter" placeholder="Ex. : Emma" value="${esc(UI.studentFilter)}" /></label><button class="btn btn-outline" data-action="show-archived">Voir les élèves archivés</button></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Prénom</th><th>Statut aujourd’hui</th><th>Interrogations (année)</th><th>Actions</th></tr></thead><tbody>${students.filter(s=>s.active).map((s,i)=>`<tr><td><button class="btn btn-small btn-outline" data-action="select-student" data-id="${esc(s.id)}"><span class="person-avatar" style="--avatar-bg:${avatarColor(i)};width:25px;height:25px;font-size:11px">${esc(s.name[0])}</span>${esc(s.name)}</button></td><td><button class="roster-btn ${isAbsent(s.id)?'absent':''}" data-action="toggle-absence" data-id="${esc(s.id)}">${isAbsent(s.id)?'○ Absent':'✓ Présent'}</button></td><td>${y.events.filter(e=>e.studentId===s.id).length}</td><td><button class="btn btn-small btn-outline" data-action="edit-student" data-id="${esc(s.id)}">${ic('pencil')} Modifier</button></td></tr>`).join('')||'<tr><td colspan="4">Aucun élève trouvé.</td></tr>'}</tbody></table></div></section>
 <section class="card"><h3 class="card-title">➕ Ajouter un élève</h3><form id="addStudentForm" class="field-row"><label class="field-grow"><span class="control-label">Prénom</span><input class="field" id="newStudentName" name="name" placeholder="Nouveau prénom" maxlength="100" required autocomplete="off" /></label><button class="btn btn-primary" type="submit">${ic('plus')} Ajouter</button></form><p class="inline-help mt-1">L’élève rejoint automatiquement les tirages et peut être placé sur le plan de classe.</p></section></div>
 <div class="stack"><section class="card"><div class="card-head"><h3>🌷 Fiche de l'élève</h3>${selected?`<button class="btn btn-small btn-outline" data-action="edit-student" data-id="${esc(selected.id)}">${ic('pencil')} Modifier</button>`:''}</div>${selected?profileHTML(selected.id,getStats(),true):'<div class="empty"><span class="empty-icon">👆</span><p>Cliquez sur un prénom pour ouvrir sa fiche et ses observations.</p></div>'}</section><div class="notice"><strong>🔒 Pour l’enseignante uniquement</strong><br>Les observations ne sont jamais montrées en mode vidéoprojecteur et sont incluses dans les sauvegardes privées JSON.</div></div></div>`;}
function addStudent(name){name=String(name||'').trim().replace(/\s+/g,' ');if(!name){toast('Indiquez un prénom.','error');return;}if(name.length>100){toast('Prénom trop long.','error');return;}if(yr().students.some(s=>s.active&&s.name.toLocaleLowerCase('fr')===name.toLocaleLowerCase('fr'))){toast('Ce prénom existe déjà dans la classe. Ajoutez une initiale si nécessaire.','error');return;}const s={id:uid(),name,active:true,addedOn:today()};yr().students.push(s);if(yr().attendance[today()])yr().attendance[today()][s.id]='present';UI.selectedStudentId=s.id;save();render();toast(`${name} a rejoint la classe !`);}
function editStudent(id){const s=studentById(id);if(!s)return;modal('Modifier un élève',`<label class="control-label" for="editStudentInput">Prénom</label><input class="field" id="editStudentInput" maxlength="100" value="${esc(s.name)}" /><div class="modal-actions"><button class="btn btn-danger" id="archiveStudentBtn">${ic('trash')} Archiver</button><button class="btn btn-primary" id="saveStudentBtn">Enregistrer</button></div>`);$('#saveStudentBtn').addEventListener('click',()=>{const name=$('#editStudentInput').value.trim();if(!name)return toast('Le prénom ne peut pas être vide.','error');if(yr().students.some(x=>x.id!==id&&x.active&&x.name.toLocaleLowerCase('fr')===name.toLocaleLowerCase('fr')))return toast('Un autre élève porte déjà ce prénom.','error');s.name=name;save();closeModal();render();toast('Prénom modifié.');});$('#archiveStudentBtn').addEventListener('click',()=>{closeModal();confirmDialog('Archiver cet élève',`Archiver ${s.name} ? Il ne participera plus aux nouveaux tirages, mais tout son historique restera conservé.`,()=>{s.active=false;s.archivedOn=today();yr().round=yr().round.filter(x=>x!==id);yr().layouts.forEach(l=>l.items.forEach(item=>item.studentIds=(item.studentIds||[]).map(x=>x===id?null:x)));if(UI.selectedStudentId===id)UI.selectedStudentId='';save();render();toast('Élève archivé.');},{danger:true,label:'Archiver'});});}
function showArchived(){const archived=yr().students.filter(s=>!s.active);modal('Élèves archivés',archived.length?archived.map(s=>`<div class="year-item"><span><strong>${esc(s.name)}</strong><br><small class="muted">Historique préservé</small></span><button class="btn btn-small btn-soft" data-action="restore-student" data-id="${esc(s.id)}">Restaurer</button></div>`).join(''):'<p>Aucun élève archivé dans cette classe.</p>');}
function newObservation(id){const s=studentById(id);if(!s)return;modal(`Observation : ${s.name}`,`<form id="observationForm"><label class="control-label" for="observationLabel">Appréciation</label><select id="observationLabel" class="field"><option>En progrès</option><option>À l’aise</option><option>À accompagner</option><option>Observation libre</option></select><label class="control-label mt-2" for="observationSubject">Matière (facultatif)</label><select class="field" id="observationSubject"><option value="">Sans matière</option>${subjects().filter(x=>x!=='Sans matière').map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select><label class="control-label mt-2" for="observationText">Note privée (facultative)</label><textarea id="observationText" class="field" maxlength="1200" placeholder="Ce que j’ai observé aujourd’hui…"></textarea><div class="modal-actions"><button type="button" class="btn btn-outline" data-action="close-modal">Annuler</button><button type="submit" class="btn btn-primary">${ic('check')} Enregistrer</button></div></form>`);$('#observationForm').addEventListener('submit',e=>{e.preventDefault();yr().observations.push({id:uid(),studentId:id,label:$('#observationLabel').value,subject:$('#observationSubject').value,text:$('#observationText').value.trim(),at:new Date().toISOString(),day:today()});save();closeModal();render();toast('Observation privée enregistrée.');});}
/* ─────────────────────── Plan de classe ─────────────────────── */
const ITEM_TYPES={desk1:{name:'Table individuelle',emoji:'▤',width:14,height:15,seats:1},desk2:{name:'Table double',emoji:'▥',width:22,height:15,seats:2},desk4:{name:'Îlot de quatre',emoji:'▦',width:26,height:23,seats:4},teacher:{name:'Bureau maîtresse',emoji:'👩‍🏫',width:18,height:11,seats:0},board:{name:'Tableau',emoji:'▭',width:37,height:9,seats:0},door:{name:'Porte',emoji:'🚪',width:7,height:14,seats:0},window:{name:'Fenêtre',emoji:'🪟',width:17,height:7,seats:0}};
function layoutItemHTML(item){const type=ITEM_TYPES[item.type]||ITEM_TYPES.desk2,selected=UI.selectedLayoutItemId===item.id;const seats=item.studentIds||[];const contents=type.seats?`<div class="desk-piece ${type.seats===4?'four':''}"><div class="desk-seats" style="--columns:${type.seats===4?2:type.seats}">${Array.from({length:type.seats},(_,i)=>{const id=seats[i],s=studentById(id);return `<span class="desk-seat ${id&&(UI.pending?.studentId===id||UI.lastResult?.studentId===id)?'highlight':''} ${id&&isAbsent(id)?'absent':''}" title="${esc(s?.name||'Place libre')}">${esc(s?.name||'+')}</span>`}).join('')}</div></div>`:`<div class="other-piece ${esc(item.type)}">${type.emoji}<br>${esc(type.name.replace('Bureau maîtresse','Bureau'))}</div>`;return `<div class="layout-item ${selected?'selected':''}" data-drag-id="${esc(item.id)}" style="left:${item.x}%;top:${item.y}%;width:${type.width}%;height:${type.height}%;--rotate:${item.rotation||0}deg" role="button" tabindex="0" aria-label="${esc(type.name)}. Cliquer pour modifier et glisser pour déplacer">${contents}</div>`;}
function inspectorHTML(){const layout=getLayout(),item=layout?.items.find(i=>i.id===UI.selectedLayoutItemId);if(!item)return `<div class="empty"><span class="empty-icon">👆</span><h3>Choisissez un élément</h3><p>Cliquez sur une table ou un meuble pour le déplacer, le faire pivoter ou attribuer des élèves.</p></div>`;const type=ITEM_TYPES[item.type];return `<div class="tiny-row"><strong>${type.emoji} ${esc(type.name)}</strong><span class="chip sage">Sélectionné</span></div><div class="field-row mt-2"><button class="btn btn-outline btn-small" data-action="rotate-item" data-id="${esc(item.id)}">${ic('rotate')} Rotation 90°</button><button class="btn btn-danger btn-small" data-action="delete-item" data-id="${esc(item.id)}">${ic('trash')} Retirer</button></div>${type.seats?`<div class="divider"></div><h4>Les élèves à cette table</h4>${Array.from({length:type.seats},(_,i)=>`<label class="seat-select-row"><span>Place ${i+1}</span><select class="field" data-seat-index="${i}"><option value="">Place libre</option>${activeStudents().map(s=>`<option value="${esc(s.id)}" ${item.studentIds?.[i]===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`).join('')}<p class="inline-help mt-1">Un même élève ne peut pas occuper deux tables. Il est déplacé automatiquement si vous changez sa place.</p>`:''}`;}
function renderLayout(){const layout=getLayout();return `${pageHeading('MON ESPACE À MOI','Mon plan de classe 🏫','Reproduisez votre salle : ajoutez des tables, placez les élèves et déplacez librement les meubles.',`<button class="btn btn-outline" data-action="new-layout">${ic('plus')} Nouvelle disposition</button>`)}
 <div class="card mb-2"><div class="field-row"><label class="field-grow"><span class="control-label">Disposition actuelle</span><select class="field" id="layoutSelect">${yr().layouts.map(l=>`<option value="${esc(l.id)}" ${l.id===layout.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><button class="btn btn-outline" data-action="rename-layout">${ic('pencil')} Renommer</button><button class="btn btn-outline" data-action="new-layout">${ic('plus')} Dupliquer / Nouveau</button></div><p class="inline-help mt-1">Chaque disposition est sauvegardée automatiquement. Dupliquez le plan avant de changer les places en début de période.</p></div>
 <div class="layout-screen"><div class="stack"><div class="layout-board-wrap"><div class="tiny-row mb-2"><h3>📐 ${esc(layout.name)}</h3><span class="chip sage">Glisser-déposer</span></div><div class="layout-board" id="layoutBoard" aria-label="Plan de classe personnalisable">${layout.items.map(layoutItemHTML).join('')}</div><p class="inline-help mt-1">Astuce : touchez une table pour lui attribuer des élèves ; maintenez et déplacez pour la repositionner.</p></div><div class="notice"><strong>✨ Relié au tirage</strong><br>Après un tirage, la place de l'élève sélectionné s'illumine sur le plan. Ses absences apparaissent en gris. Le plan n'altère jamais l'historique des interrogations.</div></div>
 <div class="stack"><section class="card"><h3 class="card-title">🪄 Ajouter dans ma salle</h3><div class="layout-toolbox">${Object.entries(ITEM_TYPES).map(([id,type])=>`<button class="layout-add" data-action="add-layout-item" data-type="${id}"><span>${type.emoji}</span>${esc(type.name)}</button>`).join('')}</div></section><section class="card inspector-card"><h3 class="card-title">✏️ Modifier ma sélection</h3><div id="layoutInspector">${inspectorHTML()}</div></section></div></div>`;}
function setupBoardDnD(){const board=$('#layoutBoard');if(!board)return;let drag=null;board.addEventListener('pointerdown',e=>{const el=e.target.closest('[data-drag-id]');if(!el)return;const id=el.dataset.dragId;UI.selectedLayoutItemId=id;$$('.layout-item',board).forEach(x=>x.classList.toggle('selected',x===el));renderInspectorOnly();const item=getLayout().items.find(i=>i.id===id);if(!item)return;drag={id,el,item,x:e.clientX,y:e.clientY,startX:item.x,startY:item.y,moved:false};try{el.setPointerCapture(e.pointerId)}catch(err){};});board.addEventListener('pointermove',e=>{if(!drag)return;const rect=board.getBoundingClientRect();if(Math.abs(e.clientX-drag.x)+Math.abs(e.clientY-drag.y)>4)drag.moved=true;if(!drag.moved)return;const w=ITEM_TYPES[drag.item.type]?.width||15,h=ITEM_TYPES[drag.item.type]?.height||15;drag.item.x=Math.min(100-w,Math.max(0,drag.startX+100*(e.clientX-drag.x)/rect.width));drag.item.y=Math.min(100-h,Math.max(0,drag.startY+100*(e.clientY-drag.y)/rect.height));drag.el.style.left=drag.item.x+'%';drag.el.style.top=drag.item.y+'%';});const end=()=>{if(!drag)return;if(drag.moved)save();drag=null;};board.addEventListener('pointerup',end);board.addEventListener('pointercancel',end);board.addEventListener('keydown',e=>{const el=e.target.closest('[data-drag-id]');if(!el||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const item=getLayout().items.find(x=>x.id===el.dataset.dragId);if(!item)return;const w=ITEM_TYPES[item.type].width,h=ITEM_TYPES[item.type].height;item.x=Math.max(0,Math.min(100-w,item.x+(e.key==='ArrowRight'?2:e.key==='ArrowLeft'?-2:0)));item.y=Math.max(0,Math.min(100-h,item.y+(e.key==='ArrowDown'?2:e.key==='ArrowUp'?-2:0)));el.style.left=item.x+'%';el.style.top=item.y+'%';save();});}
function renderInspectorOnly(){const div=$('#layoutInspector');if(div)div.innerHTML=inspectorHTML();}
function addLayoutItem(type){const def=ITEM_TYPES[type];if(!def)return;const l=getLayout();const count=l.items.filter(item=>item.type===type).length;const item={id:uid(),type,x:Math.min(100-def.width,10+(count*14)%66),y:Math.min(100-def.height,17+(count*17)%63),rotation:0,studentIds:Array(def.seats).fill(null)};l.items.push(item);UI.selectedLayoutItemId=item.id;save();render();toast(`${def.name} ajouté. Glissez-le à sa place !`);}
function assignSeat(idx,id){const l=getLayout(),item=l.items.find(x=>x.id===UI.selectedLayoutItemId);if(!item||!ITEM_TYPES[item.type].seats)return;if(id){l.items.forEach(other=>{other.studentIds=(other.studentIds||[]).map(x=>x===id?null:x)});}item.studentIds[idx]=id||null;save();renderInspectorOnly();const board=$('#layoutBoard');if(board)board.innerHTML=l.items.map(layoutItemHTML).join('');toast('Plan de classe mis à jour.');}
function createLayout(){modal('Nouvelle disposition',`<p>Dupliquez le plan actuel pour changer les places sans perdre l'ancienne disposition, ou créez un plan vide.</p><label class="control-label" for="layoutNameInput">Nom de la disposition</label><input class="field" id="layoutNameInput" maxlength="70" placeholder="Période 2 – novembre" value="Disposition ${yr().layouts.length+1}" /><label class="toggle mt-2"><input id="copyLayout" type="checkbox" checked /> Copier mon plan actuel (tables et élèves)</label><div class="modal-actions"><button class="btn btn-outline" data-action="close-modal">Annuler</button><button class="btn btn-primary" id="confirmLayout">Créer la disposition</button></div>`);$('#confirmLayout').addEventListener('click',()=>{const name=$('#layoutNameInput').value.trim();if(!name)return toast('Indiquez un nom.','error');if(yr().layouts.some(l=>l.name.toLowerCase()===name.toLowerCase()))return toast('Ce nom existe déjà.','error');const src=$('#copyLayout').checked?clone(getLayout()):initialLayout();src.id=uid();src.name=name;src.items.forEach(i=>i.id=uid());yr().layouts.push(src);yr().activeLayoutId=src.id;UI.selectedLayoutItemId='';save();closeModal();render();toast('Nouvelle disposition créée.');});}
function renameLayout(){modal('Renommer la disposition',`<label class="control-label" for="layoutRename">Nom</label><input class="field" id="layoutRename" maxlength="70" value="${esc(getLayout().name)}" /><div class="modal-actions"><button class="btn btn-outline" data-action="close-modal">Annuler</button><button class="btn btn-primary" id="saveLayoutName">Enregistrer</button></div>`);$('#saveLayoutName').addEventListener('click',()=>{const n=$('#layoutRename').value.trim();if(!n)return toast('Indiquez un nom.','error');getLayout().name=n;save();closeModal();render();});}
/* ───────────────────── Calendrier et historique ───────────────────── */
function calendarHTML(){const first=dateObj(UI.calendarMonth),offset=(first.getDay()+6)%7,lastDay=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();const monthLabel=first.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});const start=offset;let cells='';for(let i=0;i<Math.ceil((offset+lastDay)/7)*7;i++){const day=i-offset+1;if(day<1||day>lastDay){cells+='<span class="calendar-cell empty-day" aria-hidden="true"></span>';continue;}const date=isoDay(new Date(first.getFullYear(),first.getMonth(),day)),num=yr().events.filter(e=>eventDay(e)===date).length,hasAbs=Object.values(yr().attendance[date]||{}).some(x=>x==='absent');cells+=`<button class="calendar-cell ${num?'active-day':''} ${date===UI.calendarSelected?'selected':''}" data-action="history-day" data-date="${date}" aria-label="${fmtDate(date)} : ${num} interrogations"><span class="day-number">${day}</span>${num?`<span class="day-count">${num} tirage${num>1?'s':''}</span>`:''}${hasAbs?'<span class="day-absence" title="Au moins une absence"></span>':''}</button>`;}return `<div class="tiny-row mb-2"><button class="icon-btn" data-action="calendar-prev" aria-label="Mois précédent">${ic('left')}</button><h3 class="month-title" style="text-transform:capitalize">${monthLabel}</h3><button class="icon-btn" data-action="calendar-next" aria-label="Mois suivant">${ic('right')}</button></div><div class="calendar-grid">${['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(d=>`<div class="calendar-day-head">${d}</div>`).join('')}${cells}</div>`;}
function renderHistory(){const d=UI.calendarSelected,events=yr().events.filter(e=>eventDay(e)===d).sort((a,b)=>b.at.localeCompare(a.at)),attendance=yr().attendance[d],known=!!attendance;return `${pageHeading('SOUVENIRS DE CLASSE','Mon historique 📅','Retrouvez chaque interrogation, modifiez les absences passées et corrigez les erreurs.',`<button class="btn btn-outline" data-action="export-csv">${ic('download')} Exporter en CSV</button>`)}
 <div class="calendar-shell"><section class="card">${calendarHTML()}<div class="notice mt-2"><strong>🌸 Comment lire ce calendrier ?</strong><br>Le nombre affiché correspond aux interrogations confirmées ; le petit point rose signale une absence enregistrée.</div></section><div class="stack"><section class="card"><div class="card-head"><h3>📖 ${fmtDate(d)}</h3><span class="chip sage">${events.length} interrogations</span></div>${events.length?events.map(e=>`<div class="history-line"><span class="history-time">${new Date(e.at).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</span><div class="history-main"><strong>${esc(studentById(e.studentId)?.name||'Élève archivé')}</strong><small>${esc(e.subject||'Sans matière')} · ${e.mode==='fair'?'Tirage équitable':e.mode==='manual'?'Ajout manuel':'Tirage aléatoire'}${e.questionText?' · Question enregistrée':''}</small>${e.questionText?`<p class="small muted">📖 ${esc(e.questionText)}</p>`:''}</div><button class="history-delete" data-action="delete-event" data-id="${esc(e.id)}" title="Supprimer cette interrogation" aria-label="Supprimer cette interrogation">${ic('trash')}</button></div>`).join(''):'<div class="empty"><div class="empty-icon">📅</div><p>Aucune interrogation enregistrée pour cette journée.</p></div>'}<button class="btn btn-soft btn-small mt-2" data-action="manual-event">${ic('plus')} Ajouter une interrogation oubliée</button></section>
 <section class="card"><div class="card-head"><h3>🏡 Présences du jour ${help('attendance')}</h3><span class="chip peach">${known?'Enregistrées':'Non enregistrées'}</span></div>${known?`<div class="roster-list">${yr().students.filter(s=>attendance[s.id]).map((s,i)=>`<div class="roster-row"><span class="roster-name">${esc(s.name)}</span><button class="roster-btn ${attendance[s.id]==='absent'?'absent':''}" data-action="history-absence" data-id="${esc(s.id)}" data-date="${d}">${attendance[s.id]==='absent'?'Absent':'Présent'}</button></div>`).join('')}</div>`:`<div class="notice">Aucune présence n'a été enregistrée ce jour. Le site ne suppose pas que tous les élèves étaient présents.</div><button class="btn btn-outline btn-small mt-2" data-action="create-attendance-day">${ic('plus')} Enregistrer cette journée</button>`}</section></div></div>`;}
function moveCalendar(monthDelta){const d=dateObj(UI.calendarMonth);d.setMonth(d.getMonth()+monthDelta,1);UI.calendarMonth=isoDay(d);UI.calendarSelected=UI.calendarMonth;render();}
function deleteHistoryEvent(id){const y=yr(),event=y.events.find(e=>e.id===id);if(!event)return;const student=studentById(event.studentId);confirmDialog('Corriger l’historique',`Supprimer l’interrogation de ${student?.name||'cet élève'} du ${fmtDate(eventDay(event))} ? Les statistiques seront recalculées.`,()=>{y.events=y.events.filter(e=>e.id!==id);if(eventDay(event)===today()&&!y.events.some(e=>e.studentId===event.studentId&&eventDay(e)===today()))y.round=y.round.filter(s=>s!==event.studentId);if(UI.lastResult?.id===id)UI.lastResult=null;save();render();toast('Interrogation supprimée.');},{danger:true,label:'Supprimer'});}
function manualEvent(){const d=UI.calendarSelected;if(!yr().students.length){toast('Ajoutez d’abord des élèves.','error');return;}modal('Ajouter une interrogation oubliée',`<form id="manualEventForm"><label class="control-label" for="manualStudent">Élève</label><select id="manualStudent" class="field" required>${yr().students.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select><label class="control-label mt-2" for="manualSubject">Matière</label><select id="manualSubject" class="field">${subjectOptions(S.subject||'Sans matière')}</select><label class="control-label mt-2" for="manualDate">Date</label><input id="manualDate" type="date" class="field" value="${d}" max="${today()}" required /><div class="modal-actions"><button type="button" class="btn btn-outline" data-action="close-modal">Annuler</button><button type="submit" class="btn btn-primary">Enregistrer</button></div></form>`);$('#manualEventForm').addEventListener('submit',e=>{e.preventDefault();const date=$('#manualDate').value;if(!date||date>today())return toast('Date incorrecte.','error');ensureAttendanceDay(date);yr().events.push({id:uid(),studentId:$('#manualStudent').value,at:date===today()?new Date().toISOString():new Date(date+'T12:00:00').toISOString(),day:date,subject:$('#manualSubject').value,mode:'manual',visual:'manual',questionText:''});save();UI.calendarSelected=date;UI.calendarMonth=date.slice(0,7)+'-01';closeModal();render();toast('Interrogation ajoutée.');});}
/* ───────────────────── Banque de questions ───────────────────── */
function renderQuestions(){const questions=yr().questions.slice().sort((a,b)=>a.subject.localeCompare(b.subject,'fr'));return `${pageHeading('LES QUESTIONS MALINES','Ma banque de questions 📚','Préparez des questions par matière, puis associez-en une au tirage d’un élève.')}
 <div class="page-grid"><div class="stack"><section class="card"><div class="card-head"><h3>📖 Toutes mes questions</h3><span class="chip lav">${questions.length} question${questions.length>1?'s':''}</span></div><div class="question-list">${questions.length?questions.map(q=>`<div class="question-item"><div><span class="chip sage">${esc(q.subject)}</span><p class="question-text">${esc(q.text)}</p></div><button class="icon-btn" data-action="delete-question" data-id="${esc(q.id)}" title="Supprimer cette question">${ic('trash')}</button></div>`).join(''):'<div class="empty"><div class="empty-icon">📚</div><h3>Votre bibliothèque commence ici</h3><p>Ajoutez quelques questions de maths, de français ou d’une autre matière.</p></div>'}</div></section></div>
 <div class="stack"><section class="card"><h3 class="card-title">✨ Nouvelle question</h3><form id="questionForm"><label class="control-label" for="newQuestionSubject">Matière</label><input class="field" id="newQuestionSubject" list="subjectSuggestions" placeholder="Ex. : Mathématiques" value="${esc(S.subject&&S.subject!=='Sans matière'?S.subject:'Mathématiques')}" maxlength="65" required /><datalist id="subjectSuggestions">${subjects().filter(s=>s!=='Sans matière').map(s=>`<option value="${esc(s)}"></option>`).join('')}</datalist><label class="control-label mt-2" for="newQuestionText">La question</label><textarea class="field" id="newQuestionText" maxlength="600" placeholder="Ex. : Combien font 7 × 8 ?" required></textarea><button class="btn btn-primary mt-2" type="submit">${ic('plus')} Ajouter ma question</button></form></section><div class="notice"><strong>💡 À utiliser avec le tirage</strong><br>Sur la page « Tirage au sort », cochez « Tirer aussi une question » et choisissez la matière. La question est tirée indépendamment de l’élève et peut être affichée en mode classe.</div></div></div>`;}
/* ────────────────────── Paramètres et sauvegarde ────────────────────── */
function renderSettings(){return `${pageHeading('MES RÉGLAGES','Paramètres ⚙️','Personnalisez les animations, gérez les années scolaires et sécurisez vos données.')}
 <div class="page-grid"><div class="stack"><section class="card"><h3 class="card-title">🎨 Préférences d'affichage</h3><div class="setting-row"><span><strong>Confettis à chaque tirage</strong><small>Une animation douce pour annoncer le prénom sélectionné.</small></span><label class="toggle"><input type="checkbox" id="prefConfetti" ${S.preferences.confetti?'checked':''} aria-label="Activer les confettis"></label></div><div class="setting-row"><span><strong>Réduire les animations</strong><small>Raccourcit le suspense et supprime les confettis.</small></span><label class="toggle"><input type="checkbox" id="prefReducedMotion" ${S.preferences.reducedMotion?'checked':''} aria-label="Réduire les animations"></label></div></section>
 <section class="card"><h3 class="card-title">👩‍🏫 Prénoms de ma classe</h3><p class="muted">${activeStudents().length} élève(s) actif(s) cette année. Ajoutez les prénoms ici, un par ligne, ou gérez-les individuellement.</p><form id="bulkStudentsForm"><label class="control-label" for="bulkStudents">Coller une liste de prénoms</label><textarea class="field" id="bulkStudents" placeholder="Emma&#10;Lucas&#10;Inès" rows="5" maxlength="12000" required></textarea><div class="field-row mt-2"><button class="btn btn-primary" type="submit">${ic('plus')} Ajouter à ma classe</button><button class="btn btn-outline" type="button" data-action="manage-students">Modifier / archiver les élèves</button></div></form><p class="inline-help mt-1">Un prénom par ligne. Les doublons sont ignorés. Les élèves déjà enregistrés et leurs statistiques sont conservés.</p></section>
 <section class="card"><div class="card-head"><h3>🗂️ Mes années scolaires</h3><span class="chip sage">${S.years.length} enregistrée${S.years.length>1?'s':''}</span></div><div class="year-list">${S.years.map(y=>`<div class="year-item ${y.id===S.activeYearId?'active':''}"><div><strong>📆 ${esc(y.label)}</strong><br><span class="muted small">${y.students.length} élèves · ${y.events.length} interrogations</span></div>${y.id===S.activeYearId?'<span class="chip sage">Active</span>':`<button class="btn btn-small btn-soft" data-action="select-year" data-id="${esc(y.id)}">Ouvrir</button>`}</div>`).join('')}</div><div class="divider"></div><form id="newYearForm"><label class="control-label" for="newYearLabel">Créer une nouvelle année scolaire</label><div class="field-row"><input class="field field-grow" id="newYearLabel" placeholder="Ex. : 2027-2028" maxlength="55" required /><button type="submit" class="btn btn-primary">${ic('plus')} Créer</button></div><label class="toggle mt-2"><input id="copyStudents" type="checkbox" /> Reprendre mes élèves et mon plan actuel</label><label class="toggle mt-1"><input id="copyQuestions" type="checkbox" checked /> Reprendre ma banque de questions</label></form><p class="inline-help mt-1">Les anciennes années sont conservées intégralement. Une nouvelle année démarre avec des statistiques et des présences vierges.</p></section></div>
 <div class="stack"><section class="card"><h3 class="card-title">🛟 Mes sauvegardes ${help('stored')}</h3><div class="notice"><strong>Stockage local</strong><br>Vos données sont enregistrées automatiquement dans Chrome sur cet appareil (${backend}). GitHub Pages n’en reçoit pas de copie. Exportez régulièrement une sauvegarde.</div><div class="stack mt-2"><button class="btn btn-primary" data-action="export-json">${ic('download')} Télécharger ma sauvegarde complète</button><button class="btn btn-outline" data-action="import-json">${ic('upload')} Restaurer une sauvegarde JSON</button><button class="btn btn-outline" data-action="export-csv">${ic('download')} Exporter l'historique CSV pour Excel</button></div><p class="inline-help mt-2">Le fichier JSON contient les prénoms, les absences, les observations, les plans de classe, les questions et toutes les années scolaires. Conservez-le dans un emplacement privé.</p></section>
 <section class="card"><h3 class="card-title">🔐 Respect des données</h3><p class="muted">Le site fonctionne sans compte et n'envoie pas de données vers un serveur. Les prénoms saisis dans l’application restent dans ce navigateur. Ne publiez pas vos fichiers de sauvegarde JSON.</p><p class="muted">En cas de changement d'ordinateur, importez votre dernière sauvegarde JSON. Si vous effacez les données du navigateur sans sauvegarde, l'historique local peut être perdu.</p></section><button class="btn btn-lav" data-action="glossary">${ic('help')} Comprendre les statistiques</button></div></div>`;}
function addStudentList(raw){const names=String(raw||'').split(/\r?\n|[;,]/).map(n=>n.trim().replace(/\s+/g,' ')).filter(Boolean);if(!names.length)return toast('Saisissez au moins un prénom.','error');let added=0,duplicates=0;const seen=new Set(yr().students.filter(s=>s.active).map(s=>s.name.toLocaleLowerCase('fr')));for(const name of names){const key=name.toLocaleLowerCase('fr');if(name.length>100||seen.has(key)){duplicates++;continue;}const student={id:uid(),name,active:true,addedOn:today()};yr().students.push(student);if(yr().attendance[today()])yr().attendance[today()][student.id]='present';seen.add(key);added++;}if(added){save();render();}toast(`${added} élève(s) ajouté(s)${duplicates?` · ${duplicates} doublon(s) ou prénom(s) trop long(s) ignoré(s)`:''}.`,added?'success':'error');}
function createSchoolYear(){const label=$('#newYearLabel')?.value.trim();if(!label)return toast('Indiquez le nom de l’année.','error');if(S.years.some(y=>y.label.toLowerCase()===label.toLowerCase()))return toast('Cette année existe déjà.','error');const keep=$('#copyStudents').checked,copyQ=$('#copyQuestions').checked,old=yr(),newYear=makeYear(label,keep?old.students.filter(s=>s.active):[]);if(keep){newYear.students=old.students.filter(s=>s.active).map(s=>({...clone(s),active:true,addedOn:today(),archivedOn:undefined}));newYear.layouts=clone(old.layouts);newYear.activeLayoutId=old.activeLayoutId;const allowed=new Set(newYear.students.map(s=>s.id));newYear.layouts.forEach(l=>l.items.forEach(item=>item.studentIds=(item.studentIds||[]).map(id=>allowed.has(id)?id:null)));}if(copyQ)newYear.questions=old.questions.map(q=>({...clone(q),id:uid()}));S.years.push(newYear);S.activeYearId=newYear.id;UI.selectedStudentId='';UI.selectedLayoutItemId='';UI.lastResult=null;save();render();toast(`Année ${label} créée. Les anciens bilans sont conservés.`);}
function doImport(file){if(!file)return;if(file.size>30*1024*1024){toast('Fichier trop volumineux : maximum 30 Mo.','error');return;}const reader=new FileReader();reader.onload=()=>{let imported;try{imported=normalizeState(JSON.parse(reader.result))}catch(e){toast('Ce fichier ne correspond pas à une sauvegarde compatible.','error');return;}confirmDialog('Restaurer cette sauvegarde ?',`Cette opération remplacera toutes les données actuellement enregistrées par celles du fichier (${imported.years.length} année(s) scolaire(s)). Exportez une sauvegarde actuelle avant de continuer.`,()=>{S=imported;UI.pending=null;UI.lastResult=null;UI.selectedStudentId='';UI.selectedLayoutItemId='';UI.page='tirage';save().then(()=>{render();toast('Sauvegarde restaurée !');});},{danger:true,label:'Remplacer mes données'});};reader.onerror=()=>toast('Impossible de lire ce fichier.','error');reader.readAsText(file,'utf-8');}
function glossary(){modal('Comprendre mes statistiques',`<p>Un petit dictionnaire pour interpréter vos graphiques et comprendre les deux types de tirage. Touchez aussi les petits « ? » dans toute l’application.</p>${['random','fair','times','share','presenceRate','coverage','equity','probability','attendance'].map(k=>`<div class="glossary-entry"><strong>${esc(HELP[k].title)}</strong><p>${esc(HELP[k].body)}</p></div>`).join('')}<div class="notice"><strong>Exemple simple</strong><br>Sur 100 interrogations de la classe, si Emma a répondu 8 fois, sa part est de 8 %. Si elle a été présente 20 jours, son taux est de 8 ÷ 20 = 0,4 interrogation par jour présent. Sa chance au prochain tirage est un indicateur différent.</div>`);}
/* ─────────────────────── Gestion des interactions ─────────────────────── */
document.addEventListener('click',e=>{const pageBtn=e.target.closest('[data-page]');if(pageBtn){e.preventDefault();goPage(pageBtn.dataset.page);return;}const target=e.target.closest('[data-action]');if(!target)return;const action=target.dataset.action,id=target.dataset.id;if(action==='modal-backdrop'){if(e.target===target)closeModal();return;}if(action==='help'){const item=HELP[target.dataset.key];if(item)modal(item.title,`<p>${esc(item.body)}</p>`);return;}switch(action){
 case 'close-modal':closeModal();break;
 case 'glossary':glossary();break;
 case 'manage-students':goPage('students');break;
 case 'settings-class':goPage('settings');break;
 case 'mobile-menu':if(!$('.mobile-dim')){const dim=document.createElement('div');dim.className='mobile-dim active';dim.dataset.action='close-mobile';document.body.appendChild(dim);}$('#sidebar').classList.add('open');break;
 case 'close-mobile':$('#sidebar').classList.remove('open');$('.mobile-dim')?.remove();break;
 case 'visual':if(UI.pending||UI.animating)return toast('Terminez le tirage en cours.');S.visual=target.dataset.visual;save();render();break;
 case 'mode':if(UI.pending||UI.animating)return toast('Terminez le tirage en cours.');S.mode=target.dataset.mode;save();render();break;
 case 'draw':startDraw();break;
 case 'confirm-draw':confirmDraw();break;
 case 'cancel-draw':cancelDraw();break;
 case 'reset-round':resetRound();break;
 case 'toggle-absence':toggleAbsent(id);break;
 case 'history-absence':toggleAbsent(id,target.dataset.date);break;
 case 'probabilities':showProbabilities();break;
 case 'projector':enterProjector();break;
 case 'projector-close':exitProjector();break;
 case 'undo-last':undoLast();break;
 case 'export-json':exportJSON();break;
 case 'export-csv':exportCSV();break;
 case 'export-stats-csv':exportStatsCSV();break;
 case 'import-json':$('#importFile').click();break;
 case 'select-year':changeYear(id);break;
 case 'select-student':UI.selectedStudentId=id;render();break;
 case 'edit-student':editStudent(id);break;
 case 'restore-student':{const student=studentById(id);if(student){student.active=true;student.archivedOn=undefined;if(yr().attendance[today()])yr().attendance[today()][id]='present';save();closeModal();render();toast(`${student.name} a rejoint les élèves actifs.`)}break;}
 case 'show-archived':showArchived();break;
 case 'new-observation':newObservation(id);break;
 case 'add-layout-item':addLayoutItem(target.dataset.type);break;
 case 'new-layout':createLayout();break;
 case 'rename-layout':renameLayout();break;
 case 'rotate-item':{const item=getLayout().items.find(i=>i.id===id);if(item){item.rotation=((item.rotation||0)+90)%360;save();render();}break;}
 case 'delete-item':{const l=getLayout(),item=l.items.find(i=>i.id===id);if(item)confirmDialog('Retirer cet élément',`Retirer « ${ITEM_TYPES[item.type].name} » de ce plan ?`,()=>{l.items=l.items.filter(i=>i.id!==id);UI.selectedLayoutItemId='';save();render();},{danger:true,label:'Retirer'});break;}
 case 'calendar-prev':moveCalendar(-1);break;
 case 'calendar-next':moveCalendar(1);break;
 case 'history-day':UI.calendarSelected=target.dataset.date;render();break;
 case 'create-attendance-day':if(UI.calendarSelected>today())return toast('Cette date est dans le futur.','error');ensureAttendanceDay(UI.calendarSelected);save();render();break;
 case 'delete-event':deleteHistoryEvent(id);break;
 case 'manual-event':manualEvent();break;
 case 'delete-question':{const q=yr().questions.find(q=>q.id===id);if(q)confirmDialog('Supprimer la question',`Supprimer définitivement cette question : « ${q.text} » ? Les anciens tirages conserveront le texte de la question posée.`,()=>{yr().questions=yr().questions.filter(x=>x.id!==id);save();render();},{danger:true,label:'Supprimer'});break;}
 }});
document.addEventListener('change',e=>{const t=e.target;switch(t.id){
 case 'globalYearSelect':changeYear(t.value);break;
 case 'drawSubject':S.subject=t.value;save();break;
 case 'questionToggle':S.askQuestion=t.checked;save();break;
 case 'statsPeriod':UI.statsPeriod=t.value;render();break;
 case 'statsSubject':UI.statsSubject=t.value;render();break;
 case 'statsFrom':UI.statsFrom=t.value;if(UI.statsTo<UI.statsFrom)UI.statsTo=UI.statsFrom;render();break;
 case 'statsTo':UI.statsTo=t.value;if(UI.statsFrom>UI.statsTo)UI.statsFrom=UI.statsTo;render();break;
 case 'statsStudent':UI.selectedStudentId=t.value;render();break;
 case 'layoutSelect':yr().activeLayoutId=t.value;UI.selectedLayoutItemId='';save();render();break;
 case 'prefConfetti':S.preferences.confetti=t.checked;save();toast('Préférence enregistrée.');break;
 case 'prefReducedMotion':S.preferences.reducedMotion=t.checked;save();toast('Préférence enregistrée.');break;
 case 'importFile':doImport(t.files?.[0]);t.value='';break;
 }
 if(t.matches('[data-seat-index]'))assignSeat(Number(t.dataset.seatIndex),t.value);
});
document.addEventListener('input',e=>{if(e.target.id==='studentFilter'){UI.studentFilter=e.target.value;const pos=e.target.selectionStart;render();const field=$('#studentFilter');field?.focus({preventScroll:true});field?.setSelectionRange(pos,pos);}});
document.addEventListener('submit',e=>{if(e.target.id==='addStudentForm'){e.preventDefault();addStudent($('#newStudentName').value);}if(e.target.id==='bulkStudentsForm'){e.preventDefault();addStudentList($('#bulkStudents').value);}if(e.target.id==='newYearForm'){e.preventDefault();createSchoolYear();}if(e.target.id==='questionForm'){e.preventDefault();const subject=$('#newQuestionSubject').value.trim(),text=$('#newQuestionText').value.trim();if(!subject||!text)return toast('La matière et la question sont obligatoires.','error');yr().questions.push({id:uid(),subject,text,createdAt:new Date().toISOString()});save();render();toast('Question ajoutée à votre banque !');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#modalRoot').children.length)closeModal();else if(UI.projector)exitProjector();else if($('#sidebar').classList.contains('open')){$('#sidebar').classList.remove('open');$('.mobile-dim')?.remove();}}});
async function init(){try{let stored=await readState();if(!stored)stored=migrateLegacy()||makeState();try{S=normalizeState(stored)}catch(error){console.error('Sauvegarde corrompue',error);S=makeState();toast('Sauvegarde précédente illisible : restaurez votre fichier JSON si nécessaire.','error');}await save();if(sessionStorage.getItem('pot-magique-migrated')){sessionStorage.removeItem('pot-magique-migrated');toast('Ancienne classe importée. Les anciens tirages n’avaient pas de dates : aucun historique n’a été inventé.');}render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(error){console.error(error);$('#pageContent').innerHTML='<div class="card"><h2>Impossible de démarrer</h2><p>Vérifiez les autorisations de stockage de Chrome, puis rechargez la page.</p></div>';}}
init();
